// <auto-generated />
namespace Local_Guide_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateloca : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateloca));
        
        string IMigrationMetadata.Id
        {
            get { return "202406070514084_updateloca"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
